name: Create PR from develop to main

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --head develop --base main --state open --json number --jq 'length')
          
          if [ "$PR_EXISTS" -eq "0" ]; then
            gh pr create \
              --base main \
              --head develop \
              --title "Merge develop into main" \
              --body "This PR was automatically created by GitHub Actions when commits were pushed to the \`develop\` branch."
          else
            echo "A pull request from develop to main already exists."
          fi
